#!/bin/bash
TMP_DIR="/tmp/socscanner-v1"
REPO="https://github.com/Greedtik/soc_scanner-v1"

echo "Downloading SOC Scanner..."
rm -rf $TMP_DIR
git clone $REPO $TMP_DIR >/dev/null 2>&1

cd $TMP_DIR || exit 1
chmod +x socscan.sh
sudo bash socscan.sh "$@"
